### ISSUE TITLE
AssertionError during model training: Input shape mismatch in FeedForwardRegressionBaseline

### ISSUE THREAD

**Issue by deskk** [keenon/InferBiomechanics#14]
Hi,

I'm encountering an AssertionError when trying to train the model using main.py. The error message suggests there's a mismatch in the input shape to JOINT_CENTERS_IN_ROOT_FRAME and self.num_joints

For testing purpose, I only tried running the model with a few b3d files from the dataset.

Do you have any suggestions on how to resolve this issue? Thanks

$ python3 main.py train
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Using Geometry folder: ./Geometry
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: UNCOMMITTED CHANGES IN REPO! THIS WILL MAKE IT HARD TO REPLICATE THIS EXPERIMENT LATER
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Initializing wandb...
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
wandb: Currently logged in as: xxx. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.18.1 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.12
wandb: Run data is saved locally in ''
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run ''
wandb: ⭐️ View project at ''
wandb: 🚀 View run at ''
## Loading datasets with skeletons:
Loading skeleton 1/7 for subject ../InferBiomechanics/data/train/p8-099.b3d
Loading skeleton 2/7 for subject ../InferBiomechanics/data/train/p6-090.b3d
Loading skeleton 3/7 for subject ../InferBiomechanics/data/train/p5-084.b3d
Loading skeleton 4/7 for subject ../InferBiomechanics/data/train/p2-086.b3d
Loading skeleton 5/7 for subject ../InferBiomechanics/data/train/p1-091.b3d
Loading skeleton 6/7 for subject ../InferBiomechanics/data/train/p4-089.b3d
Loading skeleton 7/7 for subject ../InferBiomechanics/data/train/p7-085.b3d
Loading skeleton 1/2 for subject ../InferBiomechanics/data/dev/p10-087.b3d
Loading skeleton 2/2 for subject ../InferBiomechanics/data/dev/p9-088.b3d
num dofs: 37, num joints: 1, history len: 50 stride=5
self.net=Sequential(
  (0): Linear(in_features=1860, out_features=512, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=512, out_features=512, bias=True)
  (3): Sigmoid()
  (4): Linear(in_features=512, out_features=300, bias=True)
)
Checkpoint directory does not exist!
Evaluating Dev Set before epoch=0
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Unpickling AddBiomechanicsDataset copy in reader worker thread
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Unpickling AddBiomechanicsDataset copy in reader worker thread
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Unpickling AddBiomechanicsDataset copy in reader worker thread
Traceback (most recent call last):
  File "../InferBiomechanics/src/main.py", line 61, in <module>
    main()
  File "../InferBiomechanics/src/main.py", line 45, in main
    if command.run(args):
  File "../InferBiomechanics/src/cli/train.py", line 206, in run
    outputs = model(inputs)
  File "../.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "../.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "../InferBiomechanics/src/models/FeedForwardRegressionBaseline.py", line 75, in forward
    assert input[InputDataKeys.JOINT_CENTERS_IN_ROOT_FRAME].shape[-1] == self.num_joints * 3
AssertionError
Traceback (most recent call last):
  File "../InferBiomechanics/src/main.py", line 61, in <module>
    main()
  File "../InferBiomechanics/src/main.py", line 45, in main
    if command.run(args):
  File "../InferBiomechanics/src/cli/train.py", line 206, in run
    outputs = model(inputs)
  File "../.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "../.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "../Documents/research/InferBiomechanics/src/models/FeedForwardRegressionBaseline.py", line 75, in forward
    assert input[InputDataKeys.JOINT_CENTERS_IN_ROOT_FRAME].shape[-1] == self.num_joints * 3
AssertionError
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 🚀 View run '' at: ''
wandb: ️⚡ View job at ''
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ''

**Comment by LightingMc** [comment]
I am having the same issue. self.num_joints seems to be 0.
